/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MINUS = 2;
  /** RegularExpression Id. */
  int OPENCBRACKET = 3;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 4;
  /** RegularExpression Id. */
  int USING = 5;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int AS = 7;
  /** RegularExpression Id. */
  int NAME = 8;
  /** RegularExpression Id. */
  int QUOTE = 9;
  /** RegularExpression Id. */
  int ENDQUOTE = 10;
  /** RegularExpression Id. */
  int CHAR = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"{\"",
    "\"}\"",
    "\"using\"",
    "\"in\"",
    "\"as\"",
    "<NAME>",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<token of kind 16>",
  };

}
