/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MINUS = 2;
  /** RegularExpression Id. */
  int OPENCBRACKET = 3;
  /** RegularExpression Id. */
  int CLOSECBRACKET = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int USING = 6;
  /** RegularExpression Id. */
  int DOMAIN = 7;
  /** RegularExpression Id. */
  int INSIDE = 8;
  /** RegularExpression Id. */
  int NAME = 9;
  /** RegularExpression Id. */
  int QUOTE = 10;
  /** RegularExpression Id. */
  int ENDQUOTE = 11;
  /** RegularExpression Id. */
  int CHAR = 12;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"using\"",
    "\"domain\"",
    "\"inside\"",
    "<NAME>",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<token of kind 17>",
  };

}
